apiVersion: v1
kind: Service
metadata:
  name:  chandru-rtp-service
  namespace: chandru
spec:
  type: NodePort
  selector:
    app: chandru-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000